version: '3.9'
services:
  ebank-app:
    build: .
    restart: on-failure
    image: ebank-app:latest
    container_name: ebank-app
    ports:
      - "8085:8085"
    depends_on:
      - mysqldb
  mysqldb:
    restart: unless-stopped
    image: mysql
    ports:
      - "3306:3306"
    container_name: "mysqldb"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=E-BANK